[".claude/skills/claudeception"]
  type = "git-repo"
  url = "https://github.com/blader/Claudeception.git"
  # renovate: branch=main
  ref = "62dbb91d1183a866b5cf40079265c825b2695843"
  refreshPeriod = "168h"

[".local/share/cco"]
  type = "git-repo"
  url = "https://github.com/nikvdp/cco.git"
  # renovate: branch=master
  ref = "9e514ba33e36d8a51243147541f141b008b3a016"
  refreshPeriod = "168h"
