[".claude/skills/gstack"]
  type = "archive"
  url = "https://github.com/garrytan/gstack/archive/dde55103fcc42bd446d804ddc15567ced8455ac1.tar.gz"
  # renovate: branch=main
  stripComponents = 1
  refreshPeriod = "168h"

[".local/share/cco"]
  type = "archive"
  url = "https://github.com/nikvdp/cco/archive/cd007d165984699e59f27ba672cced0b8733839e.tar.gz"
  # renovate: branch=master
  stripComponents = 1
  refreshPeriod = "168h"
